/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BummyCheeringInterface,
  BummyCheeringInterfaceInterface,
} from "../../../contracts/Interface/BummyCheeringInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_momId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_dadId",
        type: "uint256",
      },
    ],
    name: "canCheerWith",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_momId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_dadId",
        type: "uint256",
      },
    ],
    name: "cheerWith",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_momId",
        type: "uint256",
      },
    ],
    name: "inviteFriend",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_bummyId",
        type: "uint256",
      },
    ],
    name: "isReadyToCheer",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_address",
        type: "address",
      },
    ],
    name: "setBummyInfoAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class BummyCheeringInterface__factory {
  static readonly abi = _abi;
  static createInterface(): BummyCheeringInterfaceInterface {
    return new utils.Interface(_abi) as BummyCheeringInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BummyCheeringInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BummyCheeringInterface;
  }
}
