/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BummyMintingInterface,
  BummyMintingInterfaceInterface,
} from "../../../contracts/Interface/BummyMintingInterface";

const _abi = [
  {
    inputs: [],
    name: "createFirstGen0Bummy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_genes",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "createPromoBummy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class BummyMintingInterface__factory {
  static readonly abi = _abi;
  static createInterface(): BummyMintingInterfaceInterface {
    return new utils.Interface(_abi) as BummyMintingInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BummyMintingInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BummyMintingInterface;
  }
}
