/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BummyAccessInterface,
  BummyAccessInterfaceInterface,
} from "../../../contracts/Interface/BummyAccessInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_newCEO",
        type: "address",
      },
    ],
    name: "setCEO",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newCOO",
        type: "address",
      },
    ],
    name: "setCOO",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class BummyAccessInterface__factory {
  static readonly abi = _abi;
  static createInterface(): BummyAccessInterfaceInterface {
    return new utils.Interface(_abi) as BummyAccessInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BummyAccessInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BummyAccessInterface;
  }
}
