/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BummyOwnershipInterface,
  BummyOwnershipInterfaceInterface,
} from "../../../contracts/Interface/BummyOwnershipInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_bummyId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_recipient",
        type: "address",
      },
    ],
    name: "rescueLostBummy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class BummyOwnershipInterface__factory {
  static readonly abi = _abi;
  static createInterface(): BummyOwnershipInterfaceInterface {
    return new utils.Interface(_abi) as BummyOwnershipInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BummyOwnershipInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as BummyOwnershipInterface;
  }
}
