/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BummyInfoInterface,
  BummyInfoInterfaceInterface,
} from "../../../contracts/Interface/BummyInfoInterface";

const _abi = [
  {
    inputs: [],
    name: "isBummyInfo",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "genes1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "genes2",
        type: "uint256",
      },
    ],
    name: "mixGenes",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class BummyInfoInterface__factory {
  static readonly abi = _abi;
  static createInterface(): BummyInfoInterfaceInterface {
    return new utils.Interface(_abi) as BummyInfoInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BummyInfoInterface {
    return new Contract(address, _abi, signerOrProvider) as BummyInfoInterface;
  }
}
