/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface BummyInfoInterfaceInterface extends utils.Interface {
  functions: {
    "isBummyInfo()": FunctionFragment;
    "mixGenes(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "isBummyInfo" | "mixGenes"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isBummyInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mixGenes",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "isBummyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mixGenes", data: BytesLike): Result;

  events: {};
}

export interface BummyInfoInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BummyInfoInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isBummyInfo(overrides?: CallOverrides): Promise<[boolean]>;

    mixGenes(
      genes1: PromiseOrValue<BigNumberish>,
      genes2: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  isBummyInfo(overrides?: CallOverrides): Promise<boolean>;

  mixGenes(
    genes1: PromiseOrValue<BigNumberish>,
    genes2: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    isBummyInfo(overrides?: CallOverrides): Promise<boolean>;

    mixGenes(
      genes1: PromiseOrValue<BigNumberish>,
      genes2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    isBummyInfo(overrides?: CallOverrides): Promise<BigNumber>;

    mixGenes(
      genes1: PromiseOrValue<BigNumberish>,
      genes2: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isBummyInfo(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    mixGenes(
      genes1: PromiseOrValue<BigNumberish>,
      genes2: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
